#!/usr/bin/env python3
"""
Compare SavedModel vs TFJS model outputs to detect conversion issues.
Since TFJS export is from SavedModel, they should produce identical results.
"""

import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import numpy as np
import tensorflow as tf
import math
import json

GRID_SIZE = 20

# Load SavedModel
print("Loading SavedModel...")
model_saved = tf.saved_model.load("ml_heuristic_savedmodel_static")
concrete_func = model_saved.signatures['serving_default']

# Load TFJS model.json to check it's complete
print("Checking TFJS model.json...")
with open("web_model_static/model.json", 'r') as f:
    tfjs_json = json.load(f)
    
print(f"  Format: {tfjs_json['format']}")
print(f"  Generated by: {tfjs_json['generatedBy']}")
print(f"  Converted by: {tfjs_json['convertedBy']}")
print(f"  Number of weights: {len(tfjs_json['weightsManifest'][0]['weights'])}")

# Check if binary file exists
if os.path.exists("web_model_static/group1-shard1of1.bin"):
    size = os.path.getsize("web_model_static/group1-shard1of1.bin")
    print(f"  Binary file size: {size} bytes")
else:
    print("  ❌ Binary file NOT FOUND!")

# Generate 5 test inputs
np.random.seed(42)
test_inputs = []
for i in range(5):
    grid = np.random.choice([0, 1], size=(GRID_SIZE, GRID_SIZE), p=[0.5, 0.5]).astype(np.float32)
    sg = np.random.uniform(0, 1, size=5).astype(np.float32)
    test_inputs.append((grid, sg))

print("\nComparing SavedModel vs Expected TFJS outputs:")
print("=" * 80)

for i, (grid, sg) in enumerate(test_inputs):
    grid_batch = grid.reshape(1, GRID_SIZE, GRID_SIZE, 1)
    sg_batch = sg.reshape(1, 5)
    
    # SavedModel prediction
    result = concrete_func(grid=tf.constant(grid_batch), start_goal=tf.constant(sg_batch))
    savedmodel_pred = result['output_0'].numpy()[0][0]
    
    print(f"\nTest {i+1}:")
    print(f"  SavedModel output: {savedmodel_pred:.6f}")
    print(f"  Input grid sum (walls): {np.sum(grid)}")
    print(f"  Input sg sample: [{sg[0]:.3f}, {sg[1]:.3f}, {sg[2]:.3f}, {sg[3]:.3f}, {sg[4]:.3f}]")
    
    # Check for anomalies
    if not np.isfinite(savedmodel_pred):
        print(f"  ❌ ANOMALY: SavedModel returned {savedmodel_pred}")
    elif savedmodel_pred < 0 or savedmodel_pred > 1:
        print(f"  ⚠️ WARNING: SavedModel output {savedmodel_pred} outside [0,1] range")
    else:
        max_cost = math.sqrt(2) * (GRID_SIZE - 1)
        pred_cost = savedmodel_pred * max_cost
        print(f"  ✓ Normalized: {pred_cost:.3f} (within expected range)")

print("\n" + "=" * 80)
print("Diagnosis: SavedModel weights and outputs are valid and finite")
